version: "3.8"
services:
  vite:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: vite_dev_container
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"